version: '3'
services:
  mydb:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ico1688.info
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: golang_app
    ports:
      - "5009:5009"
    tty: true
    depends_on:
      - mydb

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    container_name: golang_admin
    ports:
      - "5010:5010"
    tty: true
    depends_on:
      - mydb